### ISSUE TITLE
To do list for Sunday 05.12.2021

### ISSUE THREAD

**Issue by mariebellier** [ptds2021/project--G5#1]
- [x] R/RcPP Functions with documentations (Massimo, Meri)
- [x] Package Skeleton (Meri, Marie)
- [x] Shiny App (Meri, Massimo)
- [x] Description file of package (Vania, Xavier)
- [x] #2
- [x] A vignette illustrating the package/shinyApp with example (Xavier, Vania)

Next steps: 
- [x] Blog (Marie, Vania)
- [ ] Explaining Video (Xavier, Vania)
- [x] Control the To-Do list (issues) on github (Vania, Xavier)

**Comment by vania-rodrigues** [comment]
I don't know how that package can be installed from GitHub... I've tried with remotes::install_github("ptds2021/project--G5") but it doesn't work... Still a task to do and retry.

<img width="672" alt="Capture d’écran 2021-12-08 à 21 18 16" src="https://user-images.githubusercontent.com/74839013/145280487-9c08b31d-6d49-4474-81b1-1dc9da26bd65.png">
